// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMvcMysql.Data;

#nullable disable

namespace WebMvcMysql.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220317130501_Criacao-Inicial")]
    partial class CriacaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebMvcMysql.Models.Caminhao", b =>
                {
                    b.Property<int>("CaminhaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CaminhaoId");

                    b.Property<string>("CaminhaoAnoFabricacao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CaminhaoAnoFabricacao");

                    b.Property<string>("CaminhaoAnoModelo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CaminhaoAnoModelo");

                    b.Property<string>("CaminhaoModelo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CaminhaoModelo");

                    b.HasKey("CaminhaoId");

                    b.ToTable("Caminhao");
                });
#pragma warning restore 612, 618
        }
    }
}
